import type { Automation } from './types';

// ============================================================
// MASTER AUTOMATION DATABASE
// 35+ automations mapped to industries, pain points, budgets.
// Each entry is either a simple automation or an agentic framework.
// ============================================================

export const AUTOMATIONS: Automation[] = [
  // ── COMMUNICATION ──────────────────────────────────────────
  {
    id: 'ai_receptionist',
    name: 'AI Phone Receptionist',
    category: 'communication',
    description: 'An AI voice agent answers inbound calls 24/7, qualifies leads, answers FAQs, and books appointments directly into your calendar. Sounds natural, handles multiple calls simultaneously.',
    impact: 'Capture 30-50% more leads by never missing a call. Eliminate hold times and voicemail black holes.',
    estimatedSavings: '15-25 hours/week in staff phone time',
    complexity: 'medium',
    monthlyCost: '$200-$500/mo',
    icon: '📞',
    industries: [],
    painPoints: ['answering_questions', 'scheduling'],
    isAgentic: true,
  },
  {
    id: 'ai_chat_widget',
    name: 'AI Website Chat Agent',
    category: 'communication',
    description: 'A trained AI chatbot on your website answers visitor questions instantly, captures lead info, and routes complex inquiries to your team. Trained on your specific services and pricing.',
    impact: 'Convert 15-30% more website visitors into leads with instant engagement.',
    estimatedSavings: '8-15 hours/week in repetitive inquiries',
    complexity: 'easy',
    monthlyCost: '$50-$200/mo',
    icon: '💬',
    industries: [],
    painPoints: ['answering_questions', 'lead_followup'],
    isAgentic: true,
  },
  {
    id: 'sms_automation',
    name: 'Smart SMS/Text Automation',
    category: 'communication',
    description: 'Automated text message sequences for appointment reminders, follow-ups, review requests, and re-engagement campaigns. Personalized based on customer history and behavior.',
    impact: 'Reduce no-shows by 25-40% and re-engage cold leads without manual effort.',
    estimatedSavings: '5-10 hours/week',
    complexity: 'easy',
    monthlyCost: '$30-$150/mo',
    icon: '📱',
    industries: [],
    painPoints: ['scheduling', 'lead_followup'],
    isAgentic: false,
  },

  // ── SCHEDULING ─────────────────────────────────────────────
  {
    id: 'smart_scheduling',
    name: 'Intelligent Scheduling System',
    category: 'scheduling',
    description: 'Online booking that syncs with your calendar, sends automatic confirmations and reminders, handles rescheduling, and fills last-minute cancellations from a waitlist.',
    impact: 'Eliminate scheduling back-and-forth entirely. Reduce no-shows by 30%.',
    estimatedSavings: '8-12 hours/week',
    complexity: 'easy',
    monthlyCost: '$20-$100/mo',
    icon: '📅',
    industries: [],
    painPoints: ['scheduling'],
    isAgentic: false,
  },
  {
    id: 'waitlist_ai',
    name: 'AI Waitlist & Cancellation Filler',
    category: 'scheduling',
    description: 'When someone cancels, AI automatically contacts waitlisted clients in priority order, offers the slot, and books the first taker. No staff involvement needed.',
    impact: 'Recover 60-80% of cancelled appointment revenue automatically.',
    estimatedSavings: '$2,000-$8,000/month in recovered revenue',
    complexity: 'medium',
    monthlyCost: '$100-$300/mo',
    icon: '🔄',
    industries: ['medspa', 'dental', 'chiropractic', 'salon', 'massage', 'fitness', 'veterinary', 'optometry', 'mental_health', 'tattoo'],
    painPoints: ['scheduling'],
    isAgentic: true,
  },

  // ── MARKETING ──────────────────────────────────────────────
  {
    id: 'content_engine',
    name: 'AI Content Generation Engine',
    category: 'marketing',
    description: 'AI generates on-brand social media posts, email campaigns, blog content, and ad copy trained on your voice and style. Review and publish, or set to auto-post.',
    impact: 'Produce 10x more content without hiring. Stay visible on every platform.',
    estimatedSavings: '10-20 hours/week in content creation',
    complexity: 'easy',
    monthlyCost: '$30-$100/mo',
    icon: '✍️',
    industries: [],
    painPoints: ['content_creation'],
    isAgentic: false,
  },
  {
    id: 'review_management',
    name: 'AI Review Response & Reputation Manager',
    category: 'marketing',
    description: 'AI monitors new Google/Yelp reviews, drafts personalized responses within minutes, sends review request texts to happy customers, and alerts you to negative reviews.',
    impact: 'Boost Google rating by 0.3-0.5 stars in 90 days. Never leave a review unanswered.',
    estimatedSavings: '3-6 hours/week',
    complexity: 'easy',
    monthlyCost: '$50-$150/mo',
    icon: '⭐',
    industries: [],
    painPoints: ['reviews'],
    isAgentic: true,
  },
  {
    id: 'email_nurture',
    name: 'Automated Email Nurture Sequences',
    category: 'marketing',
    description: 'Multi-step email sequences that nurture leads from first contact to booking. Behavior-triggered: different paths based on what they click, open, or ignore.',
    impact: 'Convert 20-35% more leads into paying customers over 30-60 days.',
    estimatedSavings: '8-12 hours/week in manual follow-up',
    complexity: 'easy',
    monthlyCost: '$30-$200/mo',
    icon: '📧',
    industries: [],
    painPoints: ['lead_followup'],
    isAgentic: false,
  },
  {
    id: 'retargeting_automation',
    name: 'Smart Retargeting & Abandoned Cart Recovery',
    category: 'marketing',
    description: 'Automatically retarget website visitors and cart abandoners with personalized ads and email sequences. AI optimizes timing and messaging.',
    impact: 'Recover 10-15% of lost sales from abandoners and lapsed visitors.',
    estimatedSavings: '$1,000-$10,000/month in recovered revenue',
    complexity: 'medium',
    monthlyCost: '$100-$500/mo + ad spend',
    icon: '🎯',
    industries: ['ecommerce', 'medspa', 'salon', 'fitness'],
    painPoints: ['lead_followup'],
    isAgentic: false,
  },

  // ── OPERATIONS ─────────────────────────────────────────────
  {
    id: 'intake_automation',
    name: 'Digital Intake & Onboarding Automation',
    category: 'operations',
    description: 'New clients complete digital forms, sign documents, provide insurance/payment info, and receive welcome materials automatically before their first visit.',
    impact: 'Cut onboarding time by 70%. Zero paperwork at the front desk.',
    estimatedSavings: '10-15 hours/week',
    complexity: 'easy',
    monthlyCost: '$50-$200/mo',
    icon: '📝',
    industries: [],
    painPoints: ['onboarding', 'data_entry'],
    isAgentic: false,
  },
  {
    id: 'invoice_automation',
    name: 'Automated Invoicing & Payment Collection',
    category: 'operations',
    description: 'Auto-generate invoices, send payment reminders, process recurring payments, and flag overdue accounts. Syncs with your accounting software.',
    impact: 'Get paid 40% faster. Eliminate hours of manual invoicing.',
    estimatedSavings: '5-10 hours/week',
    complexity: 'easy',
    monthlyCost: '$20-$100/mo',
    icon: '💳',
    industries: [],
    painPoints: ['invoicing'],
    isAgentic: false,
  },
  {
    id: 'document_ai',
    name: 'AI Document Processing',
    category: 'operations',
    description: 'AI reads, extracts, and organizes data from documents, forms, receipts, and contracts. Auto-files into the right folders and updates your systems.',
    impact: 'Eliminate manual data entry. Process documents 10x faster with 99% accuracy.',
    estimatedSavings: '8-15 hours/week',
    complexity: 'medium',
    monthlyCost: '$50-$300/mo',
    icon: '📄',
    industries: ['legal', 'accounting', 'insurance', 'real_estate', 'property_mgmt'],
    painPoints: ['data_entry'],
    isAgentic: false,
  },
  {
    id: 'inventory_ai',
    name: 'AI Inventory & Supply Management',
    category: 'operations',
    description: 'AI tracks inventory levels, predicts demand based on trends and seasonality, auto-generates purchase orders, and alerts when stock is low.',
    impact: 'Reduce stockouts by 80% and overstock by 30%. Stop guessing inventory.',
    estimatedSavings: '5-10 hours/week + reduced waste',
    complexity: 'medium',
    monthlyCost: '$100-$400/mo',
    icon: '📦',
    industries: ['restaurant', 'ecommerce', 'medspa', 'salon', 'auto', 'pet'],
    painPoints: ['reporting'],
    isAgentic: true,
  },
  {
    id: 'workflow_automation',
    name: 'Cross-Platform Workflow Automation',
    category: 'operations',
    description: 'Connect all your tools so data flows automatically. New lead in CRM triggers email sequence, booking creates invoice, payment updates accounting.',
    impact: 'Eliminate copy-paste between tools. Every system stays in sync automatically.',
    estimatedSavings: '10-20 hours/week',
    complexity: 'medium',
    monthlyCost: '$50-$300/mo',
    icon: '⚡',
    industries: [],
    painPoints: ['data_entry', 'reporting'],
    isAgentic: false,
  },
  {
    id: 'employee_onboarding',
    name: 'Automated Employee Onboarding',
    category: 'operations',
    description: 'New hires receive automated training materials, complete digital paperwork, get system access provisioned, and follow a structured 30-day ramp plan.',
    impact: 'Cut onboarding time by 50%. New hires become productive faster.',
    estimatedSavings: '5-15 hours per new hire',
    complexity: 'easy',
    monthlyCost: '$30-$100/mo',
    icon: '🎓',
    industries: [],
    painPoints: ['onboarding', 'hiring'],
    minTeamSize: 'small',
    isAgentic: false,
  },

  // ── ANALYTICS ──────────────────────────────────────────────
  {
    id: 'business_intelligence',
    name: 'AI Business Intelligence Dashboard',
    category: 'analytics',
    description: 'AI-generated weekly reports surfacing your top revenue drivers, customer patterns, staff performance, and KPIs. No manual data entry or spreadsheet building required.',
    impact: 'Make data-driven decisions without being a data analyst. Spot trends early.',
    estimatedSavings: '5-8 hours/week in reporting',
    complexity: 'medium',
    monthlyCost: '$100-$400/mo',
    icon: '📊',
    industries: [],
    painPoints: ['reporting'],
    isAgentic: true,
  },
  {
    id: 'customer_analytics',
    name: 'Customer Behavior Analytics',
    category: 'analytics',
    description: 'Track which marketing channels drive the best customers, identify churn risk, and discover upsell opportunities based on customer behavior patterns.',
    impact: 'Focus marketing spend on what actually works. Retain 15-25% more customers.',
    estimatedSavings: '10-20% marketing cost reduction',
    complexity: 'advanced',
    monthlyCost: '$200-$600/mo',
    icon: '🔍',
    industries: [],
    painPoints: ['reporting', 'lead_followup'],
    minBudget: 'moderate',
    isAgentic: true,
  },

  // ── SALES ──────────────────────────────────────────────────
  {
    id: 'lead_scoring',
    name: 'AI Lead Scoring & Qualification',
    category: 'sales',
    description: 'AI analyzes every lead and scores them based on likelihood to convert. Hot leads get immediate attention, warm leads enter nurture sequences, cold leads get deprioritized.',
    impact: 'Focus sales efforts on the 20% of leads that drive 80% of revenue.',
    estimatedSavings: '5-10 hours/week in wasted prospecting',
    complexity: 'medium',
    monthlyCost: '$50-$300/mo',
    icon: '🏷️',
    industries: [],
    painPoints: ['lead_followup'],
    isAgentic: true,
  },
  {
    id: 'proposal_generator',
    name: 'AI Proposal & Quote Generator',
    category: 'sales',
    description: 'Generate professional, customized proposals and quotes in minutes instead of hours. AI pulls from your service catalog, pricing, and client details.',
    impact: 'Send proposals 5x faster. Win more deals by responding first.',
    estimatedSavings: '5-8 hours/week',
    complexity: 'easy',
    monthlyCost: '$30-$150/mo',
    icon: '📋',
    industries: ['home_services', 'construction', 'landscaping', 'consulting', 'marketing_agency', 'event', 'photography', 'cleaning', 'auto'],
    painPoints: ['data_entry', 'lead_followup'],
    isAgentic: false,
  },
  {
    id: 'crm_automation',
    name: 'Smart CRM Pipeline Automation',
    category: 'sales',
    description: 'Automate your entire sales pipeline. Leads get tagged, assigned, and moved through stages automatically. Reminders, follow-ups, and handoffs happen without human effort.',
    impact: 'No lead falls through the cracks. 100% follow-up coverage.',
    estimatedSavings: '8-12 hours/week',
    complexity: 'medium',
    monthlyCost: '$50-$300/mo',
    icon: '🔀',
    industries: [],
    painPoints: ['lead_followup', 'data_entry'],
    isAgentic: false,
  },

  // ── SUPPORT ────────────────────────────────────────────────
  {
    id: 'customer_support_ai',
    name: 'AI Customer Support Agent',
    category: 'support',
    description: 'An AI agent handles Tier 1 support across email, chat, and social media. Resolves common issues instantly, escalates complex ones to your team with full context.',
    impact: 'Resolve 60-80% of support tickets without human involvement.',
    estimatedSavings: '15-30 hours/week',
    complexity: 'medium',
    monthlyCost: '$150-$500/mo',
    icon: '🤖',
    industries: [],
    painPoints: ['answering_questions'],
    isAgentic: true,
  },
  {
    id: 'knowledge_base',
    name: 'Self-Service Knowledge Base with AI Search',
    category: 'support',
    description: 'A searchable help center where customers find answers themselves. AI-powered search understands questions in natural language and surfaces the right article instantly.',
    impact: 'Deflect 40-60% of support inquiries. Customers get instant answers.',
    estimatedSavings: '5-10 hours/week',
    complexity: 'easy',
    monthlyCost: '$30-$100/mo',
    icon: '📚',
    industries: [],
    painPoints: ['answering_questions'],
    isAgentic: false,
  },

  // ── HR ─────────────────────────────────────────────────────
  {
    id: 'hiring_automation',
    name: 'AI-Powered Hiring Pipeline',
    category: 'hr',
    description: 'Post jobs, screen resumes with AI, auto-schedule interviews, send rejection/offer letters, and track candidates through your pipeline automatically.',
    impact: 'Hire 2x faster. Screen 100 applicants in the time it takes to read 5.',
    estimatedSavings: '10-20 hours per open position',
    complexity: 'medium',
    monthlyCost: '$100-$400/mo',
    icon: '👔',
    industries: [],
    painPoints: ['hiring'],
    minTeamSize: 'small',
    isAgentic: true,
  },
  {
    id: 'training_ai',
    name: 'AI Training & SOPs Assistant',
    category: 'hr',
    description: 'An AI assistant your team can ask questions about company policies, procedures, and training materials. Learns from your documents and answers in real time.',
    impact: 'New hires get answers instantly instead of waiting for a manager.',
    estimatedSavings: '5-10 hours/week across team',
    complexity: 'easy',
    monthlyCost: '$50-$200/mo',
    icon: '🎯',
    industries: [],
    painPoints: ['onboarding', 'hiring'],
    minTeamSize: 'medium',
    isAgentic: true,
  },

  // ── INDUSTRY-SPECIFIC ──────────────────────────────────────
  {
    id: 'patient_reactivation',
    name: 'Patient/Client Reactivation Campaigns',
    category: 'marketing',
    description: 'AI identifies clients who haven\'t visited in a set period and sends personalized reactivation messages via text and email with special offers.',
    impact: 'Bring back 10-20% of lapsed clients within 60 days.',
    estimatedSavings: '$1,000-$5,000/month in recovered revenue',
    complexity: 'easy',
    monthlyCost: '$50-$200/mo',
    icon: '🔔',
    industries: ['medspa', 'dental', 'chiropractic', 'salon', 'massage', 'veterinary', 'optometry', 'fitness', 'mental_health', 'pet'],
    painPoints: ['lead_followup'],
    isAgentic: false,
  },
  {
    id: 'dispatch_optimization',
    name: 'AI Job Dispatch & Route Optimization',
    category: 'operations',
    description: 'AI optimizes job scheduling, route planning, and technician dispatch. Considers travel time, skill matching, parts availability, and customer preferences.',
    impact: 'Complete 15-25% more jobs per day with the same crew.',
    estimatedSavings: '5-10 hours/week + fuel savings',
    complexity: 'advanced',
    monthlyCost: '$200-$600/mo',
    icon: '🗺️',
    industries: ['home_services', 'cleaning', 'landscaping', 'construction', 'auto'],
    painPoints: ['scheduling'],
    isAgentic: true,
  },
  {
    id: 'menu_optimization',
    name: 'AI Menu Engineering & Pricing',
    category: 'analytics',
    description: 'AI analyzes sales data, food costs, and customer preferences to recommend menu changes, pricing adjustments, and specials that maximize margin.',
    impact: 'Increase average ticket size by 8-15%. Identify underperforming menu items.',
    estimatedSavings: '5-15% margin improvement',
    complexity: 'medium',
    monthlyCost: '$100-$300/mo',
    icon: '🍽️',
    industries: ['restaurant'],
    painPoints: ['reporting'],
    isAgentic: true,
  },
  {
    id: 'property_maintenance',
    name: 'AI Maintenance Request Handler',
    category: 'operations',
    description: 'Tenants submit requests via text/app. AI categorizes urgency, dispatches the right vendor, schedules the repair, and updates the tenant automatically.',
    impact: 'Resolve maintenance requests 50% faster. Zero phone tag with tenants.',
    estimatedSavings: '10-20 hours/week',
    complexity: 'medium',
    monthlyCost: '$100-$400/mo',
    icon: '🔨',
    industries: ['property_mgmt'],
    painPoints: ['answering_questions', 'scheduling'],
    isAgentic: true,
  },
  {
    id: 'legal_doc_automation',
    name: 'Legal Document Drafting Automation',
    category: 'operations',
    description: 'AI drafts standard legal documents, contracts, and letters from templates and client data. Attorney reviews and approves instead of writing from scratch.',
    impact: 'Draft documents 5-10x faster. Free attorney time for higher-value work.',
    estimatedSavings: '10-20 hours/week',
    complexity: 'medium',
    monthlyCost: '$200-$500/mo',
    icon: '⚖️',
    industries: ['legal'],
    painPoints: ['data_entry'],
    isAgentic: true,
  },
  {
    id: 'ecommerce_product_ai',
    name: 'AI Product Description & SEO Writer',
    category: 'marketing',
    description: 'AI generates optimized product descriptions, meta tags, and ad copy for your entire catalog. Bulk generation for new products, automatic SEO optimization.',
    impact: 'List products 10x faster. Improve organic search visibility by 20-40%.',
    estimatedSavings: '10-15 hours/week',
    complexity: 'easy',
    monthlyCost: '$30-$100/mo',
    icon: '🏷️',
    industries: ['ecommerce'],
    painPoints: ['content_creation'],
    isAgentic: false,
  },
  {
    id: 'social_proof_automation',
    name: 'Automated Testimonial & Case Study Collection',
    category: 'marketing',
    description: 'After successful engagements, AI sends review requests, collects testimonials, formats them for your website, and builds case study drafts automatically.',
    impact: 'Build social proof on autopilot. Double your review volume in 90 days.',
    estimatedSavings: '3-5 hours/week',
    complexity: 'easy',
    monthlyCost: '$20-$80/mo',
    icon: '🏅',
    industries: [],
    painPoints: ['reviews', 'content_creation'],
    isAgentic: false,
  },
  {
    id: 'competitive_intel',
    name: 'AI Competitive Intelligence Monitor',
    category: 'analytics',
    description: 'AI monitors competitor pricing, new services, review trends, and marketing moves. Weekly digest tells you what changed and what it means for you.',
    impact: 'Never be blindsided by a competitor move. Price and position with data.',
    estimatedSavings: '3-5 hours/week in market research',
    complexity: 'medium',
    monthlyCost: '$100-$300/mo',
    icon: '🕵️',
    industries: [],
    painPoints: ['reporting'],
    minBudget: 'moderate',
    isAgentic: true,
  },
];
